name: latinux
description: Esercizi svolti di latino e dizionario

version: 3.0.3+1303

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.3+1
  firebase_analytics: ^5.0.9
  cloud_firestore: ^0.13.0+1
  sqflite: ^1.1.8
  diacritic: ^0.1.1
  fancy_bottom_navigation: ^0.3.2
  flutter_html: ^0.11.0
  auto_size_text: ^2.1.0
  flutter_svg: ^0.15.0
  flutter_webview_plugin: ^0.3.10
  firebase_crashlytics: ^0.1.2+4
  permission: 
    git: 
      url: https://github.com/kamlesh9070/permission

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/database/esercizi.db
    - assets/images/latinux.svg

  fonts:
    - family: KeepCalm
      fonts:
        - asset: assets/fonts/KeepCalm.ttf
    - family: Roman
      fonts:
        - asset: assets/fonts/Roman.ttf
  uses-material-design: true
